clc;
close all;
n = 20;
fp = 300;
f1 = 200;
fn = 2*fp/fs;
window = blackman(n+1);
b = fir(n, fn, window);
[H, W] = freqz(b,1,128);
subplot(2,1,1);
plot(W/pi, abs(H));
title('mag res of lpf');
ylabel('gain in db');
xlabel('normalized frequency');
subplot(2,1,2);
plot(W/pi, anglr(H));
title('phase res of lpf');
ylabel('angle');
xlabel('notmalized freq');
